command gui:
    trigger:
        set {_pl} to player
        open virtual chest inventory to {_pl}
        format gui slot 0 of {_pl} with stone named "Wawow"
        format gui slot 1 of {_pl} with stone named "Wiwoaow" to close
        format gui slot 3 of {_pl} with stone named "Wowawi" to run {_pl} command "/gui"
        format gui slot 5 of {_pl} with stone named "Wiwowa" to run console command "/gui"
        format gui slot 6 of {_pl} with stone named "Wowiwwwow" to run function doSomething()
        format gui slot 7 of {_pl} with stone named "Wiwawooow" to close then run function doSomething()
-- Supposed to be: --
command gui:
    trigger:
        set {_pl} to player
        create a gui with virtual chest inventory:
            make gui slot 0 with stone named "Wawow"
            make gui slot 1 with stone named "Wiwoaow":
                close {_pl}'s inventory
            make gui slot 3 with stone named "Wowawi":
                make {_pl} execute "/gui"
            make gui slot 5 with stone named "Wiwowa":
                make console execute "/gui"
            make gui slot 6 with stone named "Wowiwwwow":
                doSomething()
            make gui slot 7 with stone named "Wiwawooow":
                close {_pl}'s inventory
                doSomething()
        open last created gui to {_pl}
